### ISSUE TITLE
make latexpdf support?

### ISSUE THREAD

**Issue by SeimenEll** [Arth-ur/sphinxcontrib-bitfield#1]
Hi,
it looks like there is no support for pdf generation with "make latexpdf". 
Can you confirm that?

The following error message can be seen:

> Exception occurred: File "../python3.6/sie-packages/sphinx/writers/latex.py", line 2486, in unkown_visit rais NotImplemented Error('Unknown node: ' + node.__class__.__name__)
NotImplemented Error: Unknown node: bitfield

**Comment by Arth-ur** [comment]
Hello,
I've just pushed a new release with latex support. Could you test it and let me know if it works for you?
You will need to install [cairo](https://cairosvg.org/) and upgrade the `bit-field` and `sphinxcontrib-bitfield` packages:
```
sudo apt install libcairo2
python3 -m pip install --upgrade --user cairosvg bit-field sphinxcontrib-bitfield
```

**Comment by SeimenEll** [comment]
Thanks for the fast reply and fix. 
I will test it but I have to wait till friday because i am not at work tomorrow.

**Comment by SeimenEll** [comment]
Works perfectly. Many thanks for the work, keep it going.
