### ISSUE TITLE
compact, vflip and hflip not behaving correctly

### ISSUE THREAD

**Issue by aacebedo** [Arth-ur/sphinxcontrib-bitfield#4]
Great extension ! 

I am facing two annoying bugs though. I tried to use it with the following code (from the example):
```
.. bitfield::
    :bits: 32
    :lanes: 4
    :vflip:
    :hflip:

      [
        {"name": "IPO",   "bits": 8, "attr": "RO"},
        {                 "bits": 7},
        {"name": "BRK",   "bits": 5, "attr": ["RW", "FOO"], "type": 4},
        {"name": "CPK",   "bits": 2},
        {"name": "Clear", "bits": 3, "type": 5},
        {                 "bits": 7}
      ]
```

According to this page https://observablehq.com/@drom/bitfield-testbox
I shall get this
![image](https://user-images.githubusercontent.com/1217680/210281441-6ec6c17f-69e7-4df9-bd4b-448684e8f355.png)
and I get this
![image](https://user-images.githubusercontent.com/1217680/210281559-d76cddcc-ec84-44a6-afc8-6c5a46e7a5bc.png)

In addition :compact: seems to be broken too, it has no impact.

**Comment by Arth-ur** [comment]
Hi!

I just made a new release [sphinxcontrib-bitfield v0.4.2](https://pypi.org/project/sphinxcontrib-bitfield/0.4.2/) which should fix this issue.

Could you check if it works for you?

Thanks!

**Comment by aacebedo** [comment]
Thanks that is working!
